### ISSUE TITLE
Run Lisp.go

### ISSUE THREAD

**Issue by Tauqeer20** [farinacci/lispers.net#19]
When I run the lisp.go, that's show the error which is mentioned in the attached file.
Anyone have any idea why this shows this error please help me out.

Thanks
![lisp error go](https://user-images.githubusercontent.com/110641797/208743264-ba26c083-7cde-4ac9-bbe9-746740debc0d.PNG)

**Comment by farinacci** [comment]
You should not run it that way. You uncomment the LISP_RUN_LISP_XTR line in RUN-LISP and then you run RESTART-LISP.

#                                                                               
# Run go data-plane. Called lisp-xtr.                                           
#                                                                               
#setenv LISP_RUN_LISP_XTR                                                       
#setenv LISP_USE_AF_PACKET                  

This will run the LISP data-plane using the go code.

Dino

**Comment by Tauqeer20** [comment]
After clone the repo, I try to run the lisp.go but they didnt run. As you
can mention some steps, Can i try it after clone then it will run…??? Or
there is some other method to run the go file after cloning the repo…???

Hoping to hear from you soon

Thanks

**Comment by farinacci** [comment]
Even if you have a repo cloned, the go file is precompiled and the binary is the file lisp-xtr. The only way for you to run it and make it work successfully is using the method I indicated below.

You do not have to compile any code. Use the release in ./build/latest (which is version 0.385). Do not untar the tarball in the source directory, use a directory like ~/lispers.net/.

Dino

**Comment by Tauqeer20** [comment]
I have tried the steps you mentioned earlier but still there is error. I
mentioned it in the attached folder. Any file I tried, they showed the same
error message, I also attached the GoPath and GoRoot. With that I also
mentioned that where I extract the GO folder which is in Home.In Go folder
and then src folder I clone the repo which is mentioned. Please check it
and let me know where the problem is.

Thanks and Regards
Muhammad Tauqeer

**Comment by farinacci** [comment]
> I have tried the steps you mentioned earlier but still there is error. I
> mentioned it in the attached folder. Any file I tried, they showed the same

I don't see an attachment. Show me what you did from a screen shot.

> error message, I also attached the GoPath and GoRoot. With that I also
> mentioned that where I extract the GO folder which is in Home.In Go folder
> and then src folder I clone the repo which is mentioned. Please check it
> and let me know where the problem is.

You do not have to mess with any go stuff. Unless your system needs configuration. Did you read these instructions from the build/README file?


You shouldn't have to build it but you need the libraries above.

Dino

**Comment by Tauqeer20** [comment]
Yes I read the build/readme. But still there is error. I mention snap above
if you are able to see and then tell me whats the problem.

Thanks

**Comment by farinacci** [comment]
I am reading this from email and haven't seen any error messages. I will have a look on github on Monday.

Dino

**Comment by Tauqeer20** [comment]
Ok, thanks.

**Comment by farinacci** [comment]
If you can email me the error messages to ***@***.*** that would make it simpler. Thanks.

Dino

**Comment by Tauqeer20** [comment]
Your email is hidden.

**Comment by Tauqeer20** [comment]
Send me your email that I text you there.

Thanks

**Comment by farinacci** [comment]
***@***.*** or my personal email ***@***.*** Thanks,DinoOn Dec 24, 2022, at 8:13 AM, Tauqeer20 ***@***.***> wrote:﻿
Send me your email that I text you there.

Thanks

**Comment by Tauqeer20** [comment]
Please send a message on this email that I will send you attachement “
***@***.***”.

Thanks

**Comment by Tauqeer20** [comment]
Where to clone the repository.? Is clone in the src of gol folder..?? Or we
can clone anywhere..??

**Comment by farinacci** [comment]
Sigh github filtering. Check at www.lispers.net where to send support email. DinoOn Dec 24, 2022, at 12:25 PM, Tauqeer20 ***@***.***> wrote:﻿
Where to clone the repository.? Is clone in the src of gol folder..?? Or we
can clone anywhere..??

**Comment by Tauqeer20** [comment]
What do you mean?

**Comment by farinacci** [comment]
Where to clone the repository.? Is clone in the src of gol folder..?? Or we
can clone anywhere..??Anywhere you like but you would need build a release. I suggest you use my builds. Just use this on the system you want to run it on. lispers.net-x86-release-0.585.tgzdropbox.comOr here is a docker image with everything pre installed. lispers.net-0.585-ubuntu-docker-imagedropbox.comI suggest you use the docker image and the lisp-xtr go binary will just work. Dino

**Comment by Tauqeer20** [comment]
Still not getting your point. Can we chane in the build file??

**Comment by farinacci** [comment]
> What do you mean?

Each time you include an email address in a git issues post, they star out the email address to protect user privacy.

Lets see if this works, send email to:

support  at   lispers.net

Dino

**Comment by farinacci** [comment]
Looks like it did. But the fastest way to issue resolution is to use my docker image.

**Comment by Tauqeer20** [comment]
Lets try this “mdtouqeer1996”.
Please with this write @ and gmail and .com

**Comment by Tauqeer20** [comment]
Hopefully this works.

**Comment by farinacci** [comment]
You can clone the repo, if you simply want a local copy. But you do not have to clone it if you want to run it. You can use the releases in the build/releases directory or download the tarball OR docker image. The tarball is in the docker image untar'ed and ready to run. If you bring up a docker container, the lispers.net code will just come up.

If you want to run the faster go data-plane, then modify the line I said in the RUN-LISP script.

So take these steps (its the easiest way):

(1) Download the docker image, type "docker load <image>".
(2) Run:

docker run -p 8080 --privileged --name <name> -h <name>  -v <host-dir>:/hostOS -ti lispers.net/ubuntu

(3) When you docker attach and type "pslisp" you'll see LISP running.

(4) Modify your RUN-LISP script, then type "RESTART-LISP".

(5) You'll need to configure xTR functionality in lisp.config.  Depending on what you are trying to do and configure, grab the docs/lisp.config.xtr or docs/lisp.config.xtr-nat (you are probably going to run the xTR behind a NAT/firewall device).

**Comment by farinacci** [comment]
I'm reading this issue list from git instead of email. I saw your first post. You cannot compile the lisp go code that way. You have to check how make-release.py does it. But I don't recommend it because I did not design the install process for users to build and compile the go data-plane. The go binary is in file lisp-xtr and ready to be executed.

**Comment by farinacci** [comment]
Here is another pointer to the docker image:

    https://www.dropbox.com/s/629guvr79vy8dz0/lispers.net-0.585-ubuntu-docker-image

Thanks for testing,
Dino

**Comment by Tauqeer20** [comment]
Thanks, I'll check it out.
I want to run the lisp file and they give me results of sending and
receiving msgs. I just want to run the file correctly that it give me
results thats so far I was unable to run the
