### ISSUE TITLE
latest release install issue

### ISSUE THREAD

**Issue by Bystrykha** [farinacci/lispers.net#20]
Hello, Dino! I'm student from Kazakhstan, and I have been interested in this project for some time now. For file "how-to-install-linux.txt" latest commit says "Remove cherrypy from instructions and replace with cheroot.", but when I build the project (version 0.589) on ubuntu 20.04, I get the error "Install NOT complete for ['cherrypy']" and I don't understand why...
Grazie !

**Comment by farinacci** [comment]
Thanks for reporting this. I will fix it in the next release. If you want to get release announcement, I can add you to ***@***.*** Please let me know.

Dino

**Comment by Bystrykha** [comment]
Hello, Dino! Thanks for the new release no more problems with cherrypy.
I don't tink that it is necessary add me to ***@***.***, because I check the repository regularly.
I have some problems with MSMR: when I execute RESTART-LISP, and check result with pslisp, I see this:
__________________________________________________________________________________________
root@AlexeyBs-VB:/home/alexeybs/gitClone/lispers.net/build/latest# ./pslisp 
--- lispers.net release 0.590 installed (py2) ---
PID     %CPU    %MEM    MEM     Process
14419   0.0     0.4     1.2G    -O ./lisp-core.pyo
14455   0.0     0.3     237M    lisp-mr.pyo
14467   0.0     0.3     384M    lisp-ms.pyo
__________________________________________________________________________________________
and when I follow the "https://10.0.2.15:8080/lisp/login", I can login as a root without password.
But when I go to the "https://10.0.2.15:8080/lisp/show/site", I have: "Internal Server Error". Can You say, why it happens?

**Comment by farinacci** [comment]
> Hello, Dino! Thanks for the new release no more problems with cherrypy.

Okey doke. Thanks for confirming the issue resolved. Appreciate it.

> I don't tink that it is necessary add me to @.***, because I check the repository regularly.
> I have some problems with MSMR: when I execute RESTART-LISP, and check result with pslisp, I see this:
> 
> ***@***.***:/home/alexeybs/gitClone/lispers.net/build/latest# ./pslisp
> --- lispers.net release 0.590 installed (py2) ---
> PID %CPU %MEM MEM Process
> 14419 0.0 0.4 1.2G -O ./lisp-core.pyo
> 14455 0.0 0.3 237M lisp-mr.pyo
> 14467 0.0 0.3 384M lisp-ms.pyo

The above output looks normal.

> and when I follow the "https://10.0.2.15:8080/lisp/login", I can login as a root without password.
> But when I go to the "https://10.0.2.15:8080/lisp/show/site", I have: "Internal Server Error". Can You say, why it happens?

I'll need more info to help you. Send me your lisp.config file on 10.0.2.15 as well as the logs/*.log. Also check in the logs directory for a lisp-traceback.log in case something crashed.

Dino

**Comment by Bystrykha** [comment]
This is my config file:
_________________________________________
 lisp enable {
    itr = no
    etr = no
    rtr = no
    map-server = yes
    map-resolver = yes
    ddt-node = no
}
lisp debug {
    etr = no
    core = no
    map-resolver = yes
    ddt-node = no
    rtr = no
    map-server = yes
    itr = no
}
lisp user-account {
    username = root
    super-user = yes
}
lisp site {
    site-name = Site-1
    authentication-key = some-key
    allowed-prefix {
        accept-more-specifics = yes
        eid-prefix = 192.168.129.0/24
    }
}
_________________________________________

This is logs from lisp-ms.log
_________________________________________
01/24/23 11:56:20.401: ms: lispers.net LISP Map-Server starting up 2023-01-24 11:56:20.401255, version 0.590, hostname ^[[1mAlexeyBs-VB^[[0m
01/24/23 11:56:20.401: ms: Local addresses are IPv4: ^[[1m^[[91m10.0.2.15^[[0m^[[0m, IPv6: ^[[1m^[[91mnone^[[0m^[[0m from device ^[[1menp0s3^[[0m, iid 0
01/24/23 11:56:21.286: ms: ^[[1mReceive^[[0m 36 bytes ^[[1mfrom lisp-core^[[0m no-port, command: 'lisp debug'
01/24/23 11:56:21.286: ms: ^[[1mEnable^[[0m process debug logging
01/24/23 11:56:21.286: ms: ^[[1mReceive^[[0m 230 bytes ^[[1mfrom lisp-core^[[0m no-port, command: 'lisp site'
01/24/23 11:56:21.287: ms: Send IPC 251-out-of-251 byte to lisp-core succeeded
01/24/23 11:56:21.291: ms: ^[[1mReceive^[[0m 36 bytes ^[[1mfrom lisp-core^[[0m no-port, command: 'lisp debug'
01/24/23 11:56:21.291: ms: ^[[1mEnable^[[0m process debug logging
01/24/23 11:56:21.291: ms: ^[[1mReceive^[[0m 162 bytes ^[[1mfrom lisp-core^[[0m no-port, command: 'lisp site'
01/24/23 11:56:21.291: ms: Send IPC 183-out-of-183 byte to lisp-core succeeded
01/24/23 11:56:48.671: ms: ^[[1mReceive^[[0m 9 bytes ^[[1mfrom lisp-core^[[0m no-port, command: 'show site'
01/24/23 11:56:48.671: ms: Send IPC 1500-out-of-2209 byte to lisp-core succeeded
01/24/23 11:56:48.671: ms: Send IPC 709-out-of-2209 byte to lisp-core succeeded
_________________________________________

This is logs from lisp-mr.log
_________________________________________
01/24/23 11:56:19.368: mr: lispers.net LISP Map-Resolver starting up 2023-01-24 11:56:19.367997, version 0.590, hostname ^[[1mAlexeyBs-VB^[[0m
01/24/23 11:56:19.368: mr: Local addresses are IPv4: ^[[1m^[[91m10.0.2.15^[[0m^[[0m, IPv6: ^[[1m^[[91mnone^[[0m^[[0m from device ^[[1menp0s3^[[0m, iid 0
01/24/23 11:56:21.286: mr: ^[[1mReceive^[[0m 38 bytes ^[[1mfrom lisp-core^[[0m no-port, command: 'lisp debug'
01/24/23 11:56:21.286: mr: ^[[1mEnable^[[0m process debug logging
01/24/23 11:56:21.291: mr: ^[[1mReceive^[[0m 38 bytes ^[[1mfrom lisp-core^[[0m no-port, command: 'lisp debug'
01/24/23 11:56:21.291: mr: ^[[1mEnable^[[0m process debug logging
_________________________________________

This is logs from lisp-core.log
_________________________________________
/home/alexeybs/gitClone/lispers.net/build/releases/release-0.590/poly1305.py:40: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
01/24/23 11:56:19.237: core: lispers.net LISP core-process starting up 2023-01-24 11:56:19.237722, version 0.590, hostname ^[[1mAlexeyBs-VB^[[0m
01/24/23 11:56:19.240: core: Local addresses are IPv4: ^[[1m^[[91m10.0.2.15^[[0m^[[0m, IPv6: ^[[1m^[[91mnone^[[0m^[[0m from device ^[[1menp0s3^[[0m, iid 0
01/24/23 11:56:19.275: core: Listen on 0::0, port 4342
01/24/23 11:56:19.276: core: Listen on 0::0, port 4341
01/24/23 11:56:19.277: core: Processing configuration file ./lisp.config
Bottle v0.12.23 server starting up (using iiIiiII1II1ii(fast=True))...
Listening on http://0.0.0.0:8080/
Hit Ctrl-C to quit.

01/24/23 11:56:19.279: core: Process the 'lisp enable' command
01/24/23 11:56:19.280: core: Start process 'lisp-mr' on Вт 24 янв 2023 11:56:19 +07
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cheroot/ssl/builtin.py", line 63, in _loopback_for_cert_thread
    server, do_handshake_on_connect=True, server_side=True,
  File "/usr/lib/python2.7/ssl.py", line 369, in wrap_socket
    _context=self)
  File "/usr/lib/python2.7/ssl.py", line 557, in __init__
    socket.__init__(self, _sock=sock._sock)
AttributeError: '_socket.socket' object has no attribute '_sock'

/home/alexeybs/gitClone/lispers.net/build/releases/release-0.590/poly1305.py:40: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
01/24/23 11:56:20.278: core: *** Process 'lisp-mr' has come up ***
01/24/23 11:56:20.283: core: Start process 'lisp-ms' on Вт 24 янв 2023 11:56:20 +07
/home/alexeybs/gitClone/lispers.net/build/releases/release-0.590/poly1305.py:40: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
01/24/23 11:56:21.285: core: Process the 'lisp debug' command
01/24/23 11:56:21.286: core: Suppress sending IPC to lisp-etr
01/24/23 11:56:21.286: core: ^[[1mDisable^[[0m process debug logging
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 876, in _handle
    return route.call(**args)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1756, in wrapper
    rv = callback(*a, **ka)
  File "lisp-core.py", line 1425, in O0o0oo0oOO0oO
  File "lispconfig.py", line 1589, in lisp_process_show_command
  File "lispconfig.py", line 196, in lisp_show_wrapper
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 4310: ordinal not in range(128)
_________________________________________

**Comment by farinacci** [comment]
A couple of comments:

(1) Please show me output of *.log using "more -R" so its more readable.
(2) Is the lisp.config have indents for the commands inside of the curly brackets?
(3) You must use the exact format as in lisp.config.example. Meaning you need to have comment lines in there and more importantly the last line being #- - - -. Copy lisp.config.example and put your changes on top of it.

Thanks,
Dino

**Comment by Bystrykha** [comment]
(1) I can't use flag -R (more: unknown parameter -R), but using "more" it seems:
lisp-core.log:
____________________________________
alexeybs@AlexeyBs-VB:~/gitClone/lispers.net/build/releases/release-0.590/logs$ more lisp-core.log
/home/alexeybs/gitClone/lispers.net/build/releases/release-0.590/poly1305.py:40: CryptographyDeprecat
ionWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated
 in cryptography, and will be removed in the next release.
01/25/23 14:34:35.292: core: lispers.net LISP core-process starting up 2023-01-25 14:34:35.292611, ve
rsion 0.590, hostname AlexeyBs-VB 
01/25/23 14:34:35.294: core: Local addresses are IPv4: 10.0.2.15, IPv6: none
 from device enp0s3, iid 0 
01/25/23 14:34:35.331: core: Listen on 0::0, port 4342 
01/25/23 14:34:35.332: core: Listen on 0::0, port 4341 
01/25/23 14:34:35.333: core: Processing configuration file ./lisp.config 
Bottle v0.12.23 server starting up (using iiIiiII1II1ii(fast=True))...
Listening on http://0.0.0.0:8080/
Hit Ctrl-C to quit.

01/25/23 14:34:35.335: core: Process the 'lisp enable' command 
01/25/23 14:34:35.336: core: Start process 'lisp-mr' on Ср 25 янв 2023 14:34:35 +07 
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cheroot/ssl/builtin.py", line 63, in _loopback_for_cer
t_thread
    server, do_handshake_on_connect=True, server_side=True,
  File "/usr/lib/python2.7/ssl.py", line 369, in wrap_socket
    _context=self)
  File "/usr/lib/python2.7/ssl.py", line 557, in __init__
    socket.__init__(self, _sock=sock._sock)
AttributeError: '_socket.socket' object has no attribute '_sock'

/home/alexeybs/gitClone/lispers.net/build/releases/release-0.590/poly1305.py:40: CryptographyDeprecat
ionWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated
 in cryptography, and will be removed in the next release.
01/25/23 14:34:36.334: core: *** Process 'lisp-mr' has come up *** 
01/25/23 14:34:36.348: core: Start process 'lisp-ms' on Ср 25 янв 2023 14:34:36 +07 
/home/alexeybs/gitClone/lispers.net/build/releases/release-0.590/poly1305.py:40: CryptographyDeprecat
ionWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated
 in cryptography, and will be removed in the next release.
01/25/23 14:34:37.349: core: Process the 'lisp debug' command 
01/25/23 14:34:37.349: core: Suppress sending IPC to lisp-etr 
01/25/23 14:34:37.349: core: Enable process debug logging 
01/25/23 14:34:37.349: core: Send IPC 60-out-of-60 byte to lisp-mr succeeded 
01/25/23 14:34:37.349: core: Suppress sending IPC to lisp-ddt 
01/25/23 14:34:37.349: core: Suppress sending IPC to lisp-rtr 
01/25/23 14:34:37.349: core: Send IPC 58-out-of-58 byte to lisp-ms succeeded 
01/25/23 14:34:37.349: core: Suppress sending IPC to lisp-itr 
01/25/23 14:34:37.349: core: Process the 'lisp user-account' command 
01/25/23 14:34:37.349: core: Process the 'lisp site' command 
01/25/23 14:34:37.349: core: Send IPC 253-out-of-253 byte to lisp-ms succeeded 
01/25/23 14:34:37.349: core: Waiting for response to config command 'lisp site' 
01/25/23 14:34:37.350: core: Receive 230 bytes from lisp-ms no-port, command 
01/25/23 14:34:37.352: core: Send command 'lisp debug' to restarting process 'lisp-mr' 
01/25/23 14:34:37.352: core: Send IPC 60-out-of-60 byte to lisp-mr succeeded 
01/25/23 14:34:37.352: core: *** Process 'lisp-ms' has come up *** 
01/25/23 14:34:37.352: core: Send command 'lisp debug' to restarting process 'lisp-ms' 
01/25/23 14:34:37.352: core: Send IPC 58-out-of-58 byte to lisp-ms succeeded 
01/25/23 14:34:37.352: core: Send command 'lisp site' to restarting process 'lisp-ms' 
01/25/23 14:34:37.352: core: Send IPC 185-out-of-185 byte to lisp-ms succeeded 
01/25/23 14:34:37.352: core: Waiting for response to config command 'lisp site' 
01/25/23 14:34:37.353: core: Receive 162 bytes from lisp-ms no-port, command 
01/25/23 14:34:42.348: core: Send IPC 30-out-of-30 byte to lisp-ms succeeded 
01/25/23 14:34:42.348: core: Waiting for response to show command 'show site' 
01/25/23 14:34:42.349: core: Received 1478-out-of-2187 byte segment from lisp-ms 
01/25/23 14:34:42.349: core: Received 709-out-of-2187 byte segment from lisp-ms 
01/25/23 14:34:42.349: core: Receive 2187 bytes from lisp-ms no-port, command 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 876, in _handle
    return route.call(**args)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1756, in wrapper
    rv = callback(*a, **ka)
  File "lisp-core.py", line 1425, in O0o0oo0oOO0oO
  File "lispconfig.py", line 1589, in lisp_process_show_command
  File "lispconfig.py", line 196, in lisp_show_wrapper
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 4304: ordinal not in range(128)
___________________________________________________

lisp-ms.log:
_______________________________________________
alexeybs@AlexeyBs-VB:~/gitClone/lispers.net/build/releases/release-0.590/logs$ more lisp-ms.log
01/25/23 14:34:36.518: ms: lispers.net LISP Map-Server starting up 2023-01-25 14:34:36.518470, versio
n 0.590, hostname AlexeyBs-VB 
01/25/23 14:34:36.519: ms: Local addresses are IPv4: 10.0.2.15, IPv6: none 
from device enp0s3, iid 0 
01/25/23 14:34:37.349: ms: Receive 36 bytes from lisp-core no-port, command: 'lisp debug'
 
01/25/23 14:34:37.349: ms: Enable process debug logging 
01/25/23 14:34:37.349: ms: Receive 230 bytes from lisp-core no-port, command: 'lisp site'
 
01/25/23 14:34:37.350: ms: Send IPC 251-out-of-251 byte to lisp-core succeeded 
01/25/23 14:34:37.352: ms: Receive 36 bytes from lisp-core no-port, command: 'lisp debug'
 
01/25/23 14:34:37.352: ms: Enable process debug logging 
01/25/23 14:34:37.352: ms: Receive 162 bytes from lisp-core no-port, command: 'lisp site'
 
01/25/23 14:34:37.353: ms: Send IPC 183-out-of-183 byte to lisp-core succeeded 
01/25/23 14:34:42.348: ms: Receive 9 bytes from lisp-core no-port, command: 'show site' 
01/25/23 14:34:42.349: ms: Send IPC 1500-out-of-2209 byte to lisp-core succeeded 
01/25/23 14:34:42.349: ms: Send IPC 709-out-of-2209 byte to lisp-core succeeded 
____________________________________________________

lisp-mr.log
____________________________________________________
01/25/23 14:34:35.424: mr: lispers.net LISP Map-Resolver starting up 2023-01-25 14:34:35.424910, vers
ion 0.590, hostname AlexeyBs-VB 
01/25/23 14:34:35.425: mr: Local addresses are IPv4: 10.0.2.15, IPv6: none 
from device enp0s3, iid 0 
01/25/23 14:34:37.349: mr: Receive 38 bytes from lisp-core no-port, command: 'lisp debug'
 
01/25/23 14:34:37.349: mr: Enable process debug logging 
01/25/23 14:34:37.352: mr: Receive 38 bytes from lisp-core no-port, command: 'lisp debug'
 
01/25/23 14:34:37.352: mr: Enable process debug logging 
____________________________________________________

(2) Yes
(3) log file:
_____________________________
#
# lispers.net lisp.config file, last changed: Ср 25 янв 2023 11:58:35 +07
#
# (1) Only commands between the first pair of dotted lines will be processed. 
#
# (2) Any lines you find prepended with "#>>>" are errors found during command 
#     processing.
#
# (3) You may comment out lines by placing a "#" in the first column of any 
#     line between the section between the first pair of dotted lines.
#
# (4) Note the modification timestamp above is auto generated after you have 
#     saved this file and it has been processed.
#
# (5) Deleting configuration can be achieved by deleting lines and restarting
#     the LISP component or by use of the LISP API.
#
# (6) The landing web page on any device provides detailed Command and API
#     documentation.
#
# (7) Any name references must follow their definitions. Examples are 
#     elp-names and rle-names when referred to in static map-cache entries.
#
# DO NOT WRITE TO ANY OTHER PART OF THIS FILE. YOU MUST ONLY ADD, CHANGE, OR
# REMOVE LINES BETWEEN THE FIRST PAIR OF DOTTED LINES SECTION.
#
# DO NOT email lisp.config files because mailers will insert \r\n rather
# than keeping this file with \n only.
#    
#-----------------------------------------------------------------------------
lisp enable {
    itr = no
    etr = no
    rtr = no
    map-server = yes
    map-resolver = yes
    ddt-node = no
}
lisp debug {
    etr = no
    core = yes
    map-resolver = yes
    ddt-node = no
    rtr = no
    map-server = yes
    itr = no
}
lisp user-account {
    username = root
#    password = =b9e5c39708999f844a3c864e863c12618bf8a3f5
#    password = pass
    super-user = yes
}
lisp site {
    site-name = Site-1
    authentication-key = some-key
    allowed-prefix {
#        instance-id = <same-as-on-database-mapping-command-on-xtr>
        accept-more-specifics = yes
        eid-prefix = 192.168.129.0/24
    }
}
#lisp site {
#    site-name = Site-2
#    authentication-key = any-key
#    allowed-prefix {
#        instance-id = <same-as-on-database-mapping-command-on-xtr>
#       eid-prefix = 10.1.1.0/24
#        accept-more-specifics = yes
#    }
#}
#lisp site {
#   site-name = <configure-a-site-behind-a-nat-that-will-register-to-you>
#    authentication-key = <same-as-on-map-server-command-on-xtr>
#    allowed-prefix {
#        instance-id = <same-as-on-database-mapping-command-on-xtr>
#       accept-more-specifics = yes
#       force-proxy-reply = yes
#       force-nat-proxy-reply = yes
#    }
#}
#-----------------------------------------------------------------------------#

**Comment by Bystrykha** [comment]
I also have a question about the code: I can't understand what is db. Is it storage of xTR or MSMR?
(scrin from lisp.py)
![image](https://user-images.githubusercontent.com/59131326/214559004-e654aa6f-957c-448b-9566-ffcfd6b0088f.png)

**Comment by farinacci** [comment]
So the ssl.py is a known problem but the API gets around the failure and the code still operates. I will have a look to see if the owners have fixed it.


> 

This is going to be a problem. You need a value for an instance-ID. If you don't care about it, it will default to 0, if you don't supply the command. That is probably the reason for the crash.


> On Jan 25, 2023, at 4:10 AM, Bystrykh Alexey ***@***.***> wrote:
> 
> 
> I also have a question about the code: I can't understand what is db. Is it storage of xTR or MSMR?
> (scrin from lisp.py)

A "db" throughout the code means it a lisp_mapping() class, created from a "lisp database-mapping" command clause.

Dino

**Comment by Bystrykha** [comment]
I fix the iid parametr, but it don't help...
config file:
![image](https://user-images.githubusercontent.com/59131326/214765665-1e002e1e-d172-4ff5-9a7c-8964e8208514.png)

**Comment by Bystrykha** [comment]
I have another question about the code:
at the moment I'm research the interaction of EID and xTR, I settled on function "lisp_process_punt" (line 19620 in lisp.py). As far as I understand, the package received from EID is processed in it and a decision is made on further actions with it. I can't understand the following piece of code:
![image](https://user-images.githubusercontent.com/59131326/214822023-6d95c2f6-ba2a-4abf-84f8-13ba2ba69c17.png)
on line 19711 it is checked if there is a record on the xTR for the source EID, then on line 19717 it is checked whether this EID is dynamic, and on line 19720 the "lisp_itr_discover_eid" function can be called, in which there is a comment "# Tell ETR process so it can register dynamic-EID.", on the basis of which, I assume that registration of a dynamic EID on ETR will follow.
The main question is: why is "lisp_itr_discover_eid" called exactly there and only after a few checks?

**Comment by farinacci** [comment]
Okay, good to rule out a bad configuration syntax. Your new lisp.config looks like it should be acceptable.

Can you try this in one of my docker images. I need to know your environment to debug it more. But try your lisp.config in a docker container using the following docker image:

  https://www.dropbox.com/s/s0pu4r7lm595woy/lispers.net-0.592-ubuntu-docker-image

Once you download it then use:

  sudo docker load -i lispers.net-0.592-ubuntu-docker-image

And start the docker container like this:

  export HN=<you-fill-in>
  sudo docker run -p 8080 --privileged --name $HN -h $HN -v /:/hostOS -ti lispers.net/ubuntu

Thanks,
Dino

**Comment by farinacci** [comment]
> I have another question about the code:

lisp_process_punt() is used by a data-plane to punt packets to the control-plane because the data-plane did not find a map-cache entry for the packet's destination.

> at the moment I'm research the interaction of EID and xTR, I settled on function "lisp_process_punt" (line 19620 in lisp.py). As far as I understand, the package received from EID is processed in it and a decision is made on further

> actions with it. I can't understand the following piece of code:

That code is doing dynamic EID discovery. So if the ITR sees a packet for an EID in a "lisp database-mapping" command with a a dynamic-eid=yes configured, it will cache the discovery an start registering the EID to the mapping system with its own RLOC. Look at docs/lisp-config-commands.txt for descriptions on the functionality configuration commands give you.

> on line 19711 it is checked if there is a record on the xTR for the source EID, then on line 19717 it is checked whether this EID is dynamic, and on line 19720 the "lisp_itr_discover_eid" function can be called, in which there is a comment "# Tell ETR process so it can register dynamic-EID.", on the basis of which, I assume that registration of a dynamic EID on ETR will follow.
> The main question is: why is "lisp_itr_discover_eid" called exactly there and only after a few checks?

Right, because if an ITR gets a packet for an EID-prefix it is not registering, it will not process the packet. When dynamic-EID=yes is configured, the EID-prefix is ONLY registered when a more specific EID is discovered.

Dino

**Comment by Bystrykha** [comment]
I tried running LISPERS using the current config file in docker container, everything went successfully
core log:
![image](https://user-images.githubusercontent.com/59131326/215036713-c20d6189-4233-4de9-9a4d-97c6b17b08be.png)
MR log:
![image](https://user-images.githubusercontent.com/59131326/215037021-396fe623-94ef-4b15-ad3e-80b42590889d.png)
MS log:
![image](https://user-images.githubusercontent.com/59131326/215037087-bd64ab69-11a6-4e8d-8a7e-1877c80c7f30.png)
Does this mean that the problem is in the my operating system (ubuntu 20.04)?

**Comment by farinacci** [comment]
In the lispers.net directory on your system, try this:

	python2 lipsers.net-test-install.pyo

And see if all the lispers.net libraries dependencies have been installed. Yes, its something with your OS.

Dino

**Comment by Bystrykha** [comment]
Maybe it's worth changing the operating system, for example, arch, fedora, or one of the previous versions of ubuntu?

**Comment by Bystrykha** [comment]
I tried to run the project on Ubuntu 18.04 and Debian 11.5.0,  the result is the same as on ubuntu 20.04... apparently, in the future I will work with containers.
Thanks for the help with the installation and the hints related to the code)
