### ISSUE TITLE
MSMR database settings

### ISSUE THREAD

**Issue by Bystrykha** [farinacci/lispers.net#22]
Hello! 
I have a question regarding the database on the MSMR: is it possible not to delete some records from the database (EID / RLOC) after their TTL expires (or make the TTL parameter infinite), or is such functionality not provided?

**Comment by farinacci** [comment]
At the moment they are not deleted. You can see that from the rows that have “no” in the Registered column. DinoOn Apr 19, 2023, at 3:05 AM, Bystrykh Alexey ***@***.***> wrote:﻿
Hello!
I have a question regarding the database on the MSMR: is it possible not to delete some records from the database (EID / RLOC) after their TTL expires (or make the TTL parameter infinite), or is such functionality not provided?
