### ISSUE TITLE
SMR message

### ISSUE THREAD

**Issue by Bystrykha** [farinacci/lispers.net#23]
Hello, Dino!
I have a question about calling SMR messages. I am running the following scenario:
  - Run MSMR, xTR_1 + dynamic host, xTR_2 + static host
  - Starting ping from a dynamic host to a static one
  - Stoping the ping. After LISP_DEFAULT_DYN_EID_TIMEOUT (15 seconds) xTR_1 stops registering the dynamic host on MSMR.

Next, I expect a Map-Request with smr_bit = True, but I don't see it in the logs or wireshark.
How do I trigger an SMR to be sent, and in which function is the smr_bit = True flag set?

Thank you!

**Comment by farinacci** [comment]
I don't support SMRs. I wanted to move to a PubSub architecture. You are welcome to try it by using "subscribe = yes" in a "lisp map-cache" command clause. If you have any issues or find bugs, I'll fix ASAP.

Dino

**Comment by Bystrykha** [comment]
Hello
I have read the LISP_PubSub specification. As I understand it, when sending a Map-Request to the MS, a subscription event occurs, then, after registering a dynamic host in a new location, the MS must send a Map-Notify message to all subscribed devices, which I do not observe ... Can you tell me, where is wromg?
These are config files:
MSMR
#-----------------------------------------------------------------------------
lisp enable {
    itr = no
    etr = no
    rtr = no
    map-server = yes
    map-resolver = yes
    ddt-node = no
}
lisp debug {
    etr = no
    core = yes
    map-resolver = yes
    ddt-node = no
    rtr = no
    map-server = yes
    itr = no
}
lisp user-account {
    username = root
    password = =b9e5c39708999f844a3c864e863c12618bf8a3f5
    super-user = yes
}
lisp site {
    site-name = site-1
    authentication-key = any-key
    allowed-prefix {
#        eid-prefix = 192.168.129.0/24
        accept-more-specifics = yes
#        echo-nonce-capable = yes
    }
#    allowed-prefix {
#        eid-prefix = 192.168.3.0/24
#        accept-more-specifics = yes
#    }
}
lisp site {
    site-name = site-2
    authentication-key = any-key
    allowed-prefix {
#        eid-prefix = 192.168.113.0/24
        accept-more-specifics = yes
#        echo-nonce-capable = yes
    }
#    allowed-prefix {
#        eid-prefix = 192.168.3.0/24
#        accept-more-specifics = yes
#    }
}
lisp site {
    site-name = site-3
    authentication-key = any-key
    allowed-prefix {
#        eid-prefix = 192.168.230.0/24
        accept-more-specifics = yes
#        echo-nonce-capable = yes
    }
}
lisp interface {
    interface-name = rloc
    device = enp0s8
}
#-----------------------------------------------------------------------------#

xTR_1 (first dynamic location)
#-----------------------------------------------------------------------------
lisp enable {
    itr = yes
    etr = yes
    rtr = no
    map-server = no
    map-resolver = no
    ddt-node = no
}
lisp debug {
    core = yes
    itr = yes
    etr = yes
    rtr = no
    map-server = no
    map-resolver = no
    ddt-node = no
}
lisp user-account {
    username = root
    password = =b9e5c39708999f844a3c864e863c12618bf8a3f5
    super-user = yes
}
lisp xtr-parameters {
    rloc-probing = no
    data-plane-security = no
    nat-traversal = no
    decentralized-nat = no
    nonce-echoing = no
    checkpoint-map-cache = no
    ipc-data-plane = no
    decentralized-push-xtr = no
    register-reachable-rtrs = no
    frame-logging = no
    flow-logging = no
    data-plane-logging = yes
}
lisp map-cache {
    prefix {
        instance-id = 0
        eid-prefix = 192.168.3.0/24
        subscribe-request = yes
    }
}
lisp database-mapping {
    prefix {
        mr-name = my-mr
        ms-name = my-ms
        eid-prefix = 192.168.129.0/24
        instance-id = 0
    }
    prefix {
        mr-name = my-mr
        ms-name = my-ms
        eid-prefix = 192.168.3.0/24
        dynamic-eid = yes
        instance-id = 0
    }
    rloc {
        address = 192.168.56.102
    }
}
lisp map-resolver {
    mr-name = my-mr
    address = 192.168.56.109
    authentication-key = any-key
    want-map-notify = yes
    site-id = 1
}
lisp interface {
    interface-name = rloc
    device = enp0s8
}
lisp interface {
    interface-name = eid_stat
    device = enp0s9
    instance-id = 0
}
lisp interface {
    interface-name = eid_bzdyn
    device = enp0s10
    instance-id = 0
    dynamic-eid = 192.168.3.0/24
}
#-----------------------------------------------------------------------------#

xTR_2 (second dynamic location)
#-----------------------------------------------------------------------------
lisp enable {
    itr = yes
    etr = yes
    rtr = no
    map-server = no
    map-resolver = no
    ddt-node = no
}
lisp debug {
    core = yes
    itr = yes
    etr = yes
    rtr = no
    map-server = no
    map-resolver = no
    ddt-node = no
}
lisp user-account {
    username = root
    password = =b9e5c39708999f844a3c864e863c12618bf8a3f5
    super-user = yes
}
lisp xtr-parameters {
    rloc-probing = no
    data-plane-security = no
    nat-traversal = no
    decentralized-nat = no
    nonce-echoing = no
    checkpoint-map-cache = no
    ipc-data-plane = no
    decentralized-push-xtr = no
    register-reachable-rtrs = no
    frame-logging = no
    flow-logging = no
    data-plane-logging = yes
}
lisp map-cache {
    prefix {
        instance-id = 0
        eid-prefix = 192.168.3.0/24
        subscribe-request = yes
    }
}
lisp database-mapping {
    prefix {
        mr-name = my-mr
        ms-name = my-ms
        eid-prefix = 192.168.113.0/24
        instance-id = 0
    }
    prefix {
        mr-name = my-mr
        ms-name = my-ms
        eid-prefix = 192.168.3.0/24
        dynamic-eid = yes
        instance-id = 0
    }
    rloc {
        address = 192.168.56.111
    }
}
lisp map-resolver {
    mr-name = my-mr
    address = 192.168.56.109
}
lisp map-server {
    ms-name = my-ms
    address = 192.168.56.109
    authentication-key = any-key
    want-map-notify = yes
    site-id = 2
}
lisp interface {
    interface-name = rloc
    device = enp0s8
}
lisp interface {
    interface-name = eid_1
    device = enp0s9
    instance-id = 0
}
lisp interface {
    interface-name = eid_bzdayn
    device = enp0s10
    instance-id = 0
    dynamic-eid = 192.168.3.0/24
}
#-----------------------------------------------------------------------------#

xTR_3 (no dynamic)
#-----------------------------------------------------------------------------
lisp enable {
    itr = yes
    etr = yes
    rtr = no
    map-server = no
    map-resolver = no
    ddt-node = no
}
lisp debug {
    core = yes
    itr = yes
    etr = yes
    rtr = no
    map-server = no
    map-resolver = no
    ddt-node = no
}
lisp user-account {
    username = root
    password = =b9e5c39708999f844a3c864e863c12618bf8a3f5
    super-user = yes
}
lisp xtr-parameters {
    rloc-probing = no
    data-plane-security = no
    nat-traversal = no
    decentralized-nat = no
    nonce-echoing = no
    checkpoint-map-cache = no
    ipc-data-plane = no
    decentralized-push-xtr = no
    register-reachable-rtrs = no
    frame-logging = no
    flow-logging = no
    data-plane-logging = no
}
lisp map-cache {
    prefix {
        instance-id = 0
        eid-prefix = 192.168.3.0/24
        subscribe-request = yes
    }
}
lisp database-mapping {
    prefix {
        mr-name = my-mr
        ms-name = my-ms
        eid-prefix = 192.168.230.0/24
        instance-id = 0
    }
    rloc {
        address = 192.168.56.104
    }
}
lisp map-resolver {
    mr-name = my-mr
    address = 192.168.56.109
}
lisp map-server {
    ms-name = my-ms
    address = 192.168.56.109
    authentication-key = any-key
    want-map-notify = yes
    site-id = 3
}
lisp interface {
    interface-name = rloc
    device = enp0s8
}
lisp interface {
    interface-name = eid_1
    device = enp0s10
    instance-id = 0
}
#-----------------------------------------------------------------------------#

This is registration dynamic host (192.168.3.5) under xTR_1(RLOC - 192.168.56.102, EID - 192.168.3.8)
![image](https://github.com/farinacci/lispers.net/assets/59131326/098df5f6-7b9b-4493-a554-465ea84b8f0e)

This is registration dynamic host (192.168.3.5) under xTR_2(RLOC - 192.168.56.111, EID - 192.168.3.9)
![image](https://github.com/farinacci/lispers.net/assets/59131326/b82c1c90-6a5e-4953-afab-f058df38aa54)

Map-cache in xTR_3 don't change
![image](https://github.com/farinacci/lispers.net/assets/59131326/b2da2472-fbb2-4421-9fa7-b21cc26d9b29)

I try did it with more specific dynamic address:
lisp map-cache {
    prefix {
        instance-id = 0
        eid-prefix = 192.168.3.5/32
        subscribe-request = yes
    }
}
but it didn't help.

**Comment by farinacci** [comment]
> I have read the LISP_PubSub specification. As I understand it, when sending a Map-Request to the MS, a subscription event occurs, then, after registering a dynamic host in a new location, the MS must send a Map-Notify message to all subscribed devices, which I do not observe ... Can you tell me, where is wromg?

Okay, some points. First conceptual:

(1) A "subscription event" is a RLOC-set change which causes the map-server to send Map-Notify messages. There is no direct connection to dynamic EIDs. But dyanmic-EIDs have the characteristic of changing RLOCs if they are roaming.

(2) A subscribe-request is a Map-Request with a bit set telling the map-server to notify you when there are RLOC-set changes. There is no explicit configuraiton in the map-server to enable PubSub. Its all driven by the xTR.

(3) You were right in configuring subscribe-request=yes. That tells the xTR when it sends a Map-Request to set the subscribe bit.

(4) It is better to use a prefix in the "lisp map-cache" so when the Map-Reply is returned for the subscribe-request the ITR installs a /32 map-cache entry. You want the prefix to be a catch-all to subscribe for all more-specifics.

(5) Make sure your map-server is proxy-replying. I didn't see you configure it.

Dynamic-EIDs:

(1) The "lisp interface" command is a white list to allow the xTR to discover which dynamic-EIDs are allowed.

(2) The "database-mapping" command instructs the ETR to not register the EID-prefix unless at least one more specific EID has been discovered that matches the EID-prefix, and then the more specific is registered (not the prefix). 

Other items:

(1) You don't need to run echo-noncing. That is a completely separate feature and not sure you want to try it or you thought it was nececessary for this use-case.

(2) You can look at the map-server web interface to inspect subscription state. Just click the MS button on the landing page. You should see a table under the registration table with subscription state.

(3) The map-cache in your XTR_3 should be a /32.

I have full support on the map-server for PubSub, but only tested it on the xTRs using lig. So I should try to do what you are doing and see if I find any bugs. Give me a couple days to do this.

I will do it with 4 containers, one an ITR that will get the Map-Notifies, one a MS, and the other two ETRs, where the dynamic-EID will roam from one to the other. I'll send you the config files when I'm done.

Please send me an lisp-itr.log file on the subcribing node as well as a lisp-ms.log on the map-server so I can get more information. Thanks.

Dino

**Comment by farinacci** [comment]
I was able to get it all to work. I will record a video for you and send you a pointer. You can learn about what I my configuration setup and show you some packet flow examples.

Dino

**Comment by Bystrykha** [comment]
Great news, I'll be waiting!
Do you still need the ITR and MS logs?

**Comment by farinacci** [comment]
> On Jun 7, 2023, at 11:26 PM, Bystrykh Alexey ***@***.***> wrote:
> 
> Great news, I'll be waiting!
> Do you still need the ITR and MS logs?

No I don’t need them. I’ll get video to you in a few hours. 

Thanks,
Dino

**Comment by farinacci** [comment]
Alexey, you can find the lispers.net <http://lispers.net/> dynamic-EID-with-pubsub video here:

    https://www.dropbox.com/s/w10fd270ou5jji9/lispers-net-dyn-eid-pubsub.mov

Please let me know what you think. Thanks.

Cheers,
Dino

**Comment by Bystrykha** [comment]
Dynamic + PubSub is working, you was right about "force-proxy-reply = yes" setting, I add this line in MSMR config file, and scenario is working.
Thank you so much for your help!

**Comment by Bystrykha** [comment]
Littl question: does PubSub use only control plane?

**Comment by farinacci** [comment]
Great to hear. Way to get it to work!

Dino

**Comment by farinacci** [comment]
> Littl question: does PubSub use only control plane?

Yes, it is an extenstion of the Map-Request (new subscribe-bit allocated) and actions performed by the map-server (when a subscribe-request is received, it keeps state). And when the RLOC-set changes for any EID-prefix that is subscribed, the map-server sends a Map-Notify message to the subscriber. Then the subscriver Map-Notify-Acks.

All those messages already existed in the LISP protocol.

That is it in a nutshell.

Dino
