### ISSUE TITLE
ipc-data-plane storages

### ISSUE THREAD

**Issue by Bystrykha** [farinacci/lispers.net#24]
I have a question about the architecture of the Lipsers with "ipc-data-plane = yes" configuration, and specifically about the map-cache and data-base storages.
I read lisp-ipc-data-plane.txt document and looked at the lispers code, after which I got the following structure: map-cache and data-base (lisp_cache object), which are in the control plane, have analogues in the data plane (in lisp.go these are Lisp_database and Lisp_map_cache structures). Changes to the storage entries from the control plane are followed by changes to the storage in the data plane, which are sent over the socket, leaving all timers (for example, 24 hours of mapcache entry retention) in the control plane.
Is this the correct understanding of storing map-cache and data-base for "ipc-data-plane = yes" ?

**Comment by farinacci** [comment]
> I have a question about the architecture of the Lipsers with "ipc-data-plane = yes" configuration, and specifically about the map-cache and data-base storages.

Sure.

> I read lisp-ipc-data-plane.txt document and looked at the lispers code, after which I got the following structure: map-cache and data-base (lisp_cache object), which are in the control plane, have analogues in the data plane (in lisp.go

Yes, correct.

> these are Lisp_database and Lisp_map_cache structures). Changes to the storage entries from the control plane are followed by changes to the storage in the data plane, which are sent over the socket, leaving all timers (for example, 24 hours of mapcache entry retention) in the control plane.

Correct.

> Is this the correct understanding of storing map-cache and data-base for "ipc-data-plane = yes" ?

Yep, you got it!

Dino
