### ISSUE TITLE
unknown AFI when processing Map-Notify with a couple prefixes

### ISSUE THREAD

**Issue by Bystrykha** [farinacci/lispers.net#26]
Hello, Dino!
I have a problem. I did lisp.config with six static prefixes. Started lispers, lispers sent map-register and received map-notify with this six prefixes, but in logs/lisp-etr.log some prefixes were not parsed correctly with "unknown-afi" error. Parsed afi equals to the last two bytes of RLOC. What's wrong and can it brake something during work?

Config:
![image](https://github.com/farinacci/lispers.net/assets/59131326/f9e5a5a4-a4dc-4842-825d-0a7cb6e2b7ec)

Wireshark parsed notify with correct prefixes:
![image](https://github.com/farinacci/lispers.net/assets/59131326/52878e6b-3d0a-4c8b-b767-93dc065dfd12)

Bad log:
![image](https://github.com/farinacci/lispers.net/assets/59131326/332af41f-01ff-4919-aa59-fdcf7d0c3360)

**Comment by farinacci** [comment]
I'm having a look. I see the nonce is byte-swampped but the semantic area of the Map-Register and Map-Notify are the same, so there must be a one-off bug in lisp_process_map_notify().

Dino

**Comment by farinacci** [comment]
I duplicated, and fix the bug you found. Thanks for reporting it. Try lispers.net release 0.602. See details from the ***@***.*** announcement.

Cheers,
Dino
